site_name: drug_toxicity
nav:
  - Home: "index.md"
  - Phase I and II: 01-phase-i-ii.ipynb

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True
  - mkdocstrings

theme:
  name: readthedocs
